apiVersion: v1
kind: Service
metadata:
  name: student-test-service
  labels:
  app: student-deployment
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      nodePort: 8090
      protocol: TCP
  selector:
    app: student-deployment